# fly.toml app configuration file generated for ohbekzat-phonebook on 2023-06-12T14:37:35+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ohbekzat-phonebook"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
