# fly.toml app configuration file generated for bloglist-ohbekzat on 2023-06-20T22:29:54+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bloglist-ohbekzat"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
