POST http://localhost:3001/api/users
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9oYmVremF0IiwiaWQiOiI2NDk1OWQxOThkODFlNjM1MTdmNGFhODUiLCJpYXQiOjE2ODc1MjgyNzV9.k-UR-KFetirpbOzdKn2-QOeO4RSrcGLJ8PP8jmB73Lo

{
    "username": "sasfaf",
    "password": "ad",
    "name": "Hohff"
}

# {
#     "title": "Notisadce us",
#     "author": "Bjdorfanie",
#     "url": "asdfaasfsdkff",
#     "likes": 12123
# }