POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9oYmVremF0MyIsImlkIjoiNjQ5YzI3NWI1ZDQ0OGM2MmI1OTllN2QxIiwiaWF0IjoxNjg3OTc5MjUxLCJleHAiOjE2ODc5ODI4NTF9.KwSW5PDHnAlQGp4evRJc0U8EHLyobhdjDqMYKhW6bdE

{
    "title": "This has beasdt3",
    "author": "Bekzat",
    "url": "asdfaasfsdkff",
    "likes": 1222123
}
