Delete http://localhost:3001/api/blogs/649c3704334610e8c6ec55eb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9oYmVremF0MyIsImlkIjoiNjQ5YzI3NWI1ZDQ0OGM2MmI1OTllN2QxIiwiaWF0IjoxNjg3OTU5Mjc1LCJleHAiOjE2ODc5NjI4NzV9.sIva3ods1GzozxvJw9GQUa4kZQ5wpdB1KQLXkggFgUE